version: '3.3'
services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ../app:/var/www
      - ../logs/app-access.log:/var/log/app-access.log
      - ../logs/app-error.log:/var/log/app-error.log
    restart: always
    ports:
      - "8090:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ../app:/var/www
    restart: always
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  database:
    image: mysql:5.6
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=ihumanne_db"
    volumes:
      - ../mysql-datadir:/var/lib/mysql
#      - ../app/localhost.sql:/docker-entrypoint-initdb.d/localhost.sql
    restart: always
    ports:
      - "33061:3306"
